export * from './moveable'
export * from './can_attack'
export * from './keyed'
export * from './magicable'
export * from './is_commander'
export * from './physical'
export * from './can_have_magical_charges'